include: package:lints/recommended.yaml
analyzer:
   exclude:
     - lib/generated/**
linter:
  rules:
    - cancel_subscriptions
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - test_types_in_equals
    - unrelated_type_equality_checks
    - valid_regexps
    - require_trailing_commas
