services:
  dart_donation_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dart_donation_bot
    volumes:
      - ./hive:/app/hive
    env_file:
      - .env
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: 100m
