version: '3.1'
services:
  dart_donation_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dart_donation_bot
    volumes:
      - ./hive:/app/hive
    environment: 
      - DISCORD_API_TOKEN=""
      - DISCORD_CHANNEL_ID=""
      - DONATION_ADDRESS=""
      - MARISMA_SERVER_HOST=""
      - MARISMA_SERVER_PORT=""
      - SILENT_OPERATION=false
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: 100m