name: dart_donation_bot
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: {color_logger: ^1.0.2, hive: ^2.2.1, nyxx: ^3.4.2, web_socket_channel: ^2.2.0}
