name: dart_donation_bot
description: A simple Discord donation bot.
version: 1.0.0
homepage: https://github.com/willyfromtheblock/dart_donation_bot

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: 
  color_logger: ^1.0.2
  grpc: ^3.2.2
  hive: ^2.2.1 
  nyxx: ^4.0.0